// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj_wYy43p9DEHmLCHESp7zl34mB3tp_hI',
    appId: '1:969079638355:web:144e69671c31a3a6c8b9a6',
    messagingSenderId: '969079638355',
    projectId: 'finalproject-15cde',
    authDomain: 'finalproject-15cde.firebaseapp.com',
    storageBucket: 'finalproject-15cde.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkPC_5vtIIBOI-AM6x4U_46n1dj-l8xvU',
    appId: '1:969079638355:android:c80ae6b142cfe9afc8b9a6',
    messagingSenderId: '969079638355',
    projectId: 'finalproject-15cde',
    storageBucket: 'finalproject-15cde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaGRT-vNlvePHZGtWaGjS7FAz-BuVeJDo',
    appId: '1:969079638355:ios:51c35d70662a3028c8b9a6',
    messagingSenderId: '969079638355',
    projectId: 'finalproject-15cde',
    storageBucket: 'finalproject-15cde.appspot.com',
    iosBundleId: 'com.example.firebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaGRT-vNlvePHZGtWaGjS7FAz-BuVeJDo',
    appId: '1:969079638355:ios:51c35d70662a3028c8b9a6',
    messagingSenderId: '969079638355',
    projectId: 'finalproject-15cde',
    storageBucket: 'finalproject-15cde.appspot.com',
    iosBundleId: 'com.example.firebaseFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj_wYy43p9DEHmLCHESp7zl34mB3tp_hI',
    appId: '1:969079638355:web:0e69eb257694fda0c8b9a6',
    messagingSenderId: '969079638355',
    projectId: 'finalproject-15cde',
    authDomain: 'finalproject-15cde.firebaseapp.com',
    storageBucket: 'finalproject-15cde.appspot.com',
  );
}
